### ISSUE TITLE
Open networks not being removed

### ISSUE THREAD

**Issue by BenKennish** [duncanje/android-open-wifi-network-remover#3]
I am using the app on the following 2 devices and it does not seem to remove open Wi-Fi networks when they are "Not in range"...

Phone: Samsung Galaxy SII (GT-I9100) with Android 4.1.2 (Jelly Bean)
Tablet: Asus Transformer Prime (TF201) with Android 4.0.3 (Ice Cream Sandwich)

Happy to throw any debug info your way if you like - I'm a systems engineer hence have a GitHub account :)

Cheers, Ben

**Comment by duncanje** [comment]
Hi,

Sorry for the late response.

Do you still experience the issue on the latest version (0.1.5.1)? Also it will only work when a disconnection occurs, so when connected to an open network -> no network or open network -> some other network. It will not work if the wifi radio is switched off.

Thanks

**Comment by BenKennish** [comment]
Thanks for writing back.

I have just updated both my tablet and phone to the latest version and will report back when I next leave an Open WiFi connection.

Cheers (and Merry Christmas if you celebrate it)
Ben

**Comment by duncanje** [comment]
No problem, let me know how you get on.
If it helps and your phone has a hotspot option you can use that to test.

Thanks,
Duncan

**Comment by BenKennish** [comment]
OK I have updated Android on my tablet so I am now testing on:

Phone: Samsung Galaxy SII (GT-I9100) with Android 4.1.2 (Jelly Bean)
Tablet: Asus Transformer Prime (TF201) with Android 4.1.1 (Jelly Bean)

However, testing seems to show that Open networks are still not being removed.  Here's an example of a test:

Created a Portable WiFi hotspot on my phone called "testing" (security set to "Open" and NOT "WPA PSK or WPA2 PSK")
Ran Open WiFi Cleaner on my tablet just to make sure it is running and working ok (which it seems to be - both "Enabled" and "Notify on connect/disconnect" are checked)
Connected to the "testing" hotspot from my tablet
Connected back to my regular WiFi network on my tablet
Result: The Open "testing" network is still listed and is not removed until I manually click to 'forget' it

Cheers,

**Comment by duncanje** [comment]
Ok, thanks. That should have worked....

I wonder if there is a bug on 4.1.x as I have only tested on 4.2 and
above...

Did you get the notifications flashing up when you connected/disconnected?

Thanks for your time,
Duncan

On 4 January 2014 19:27, Ben Kennish notifications@github.com wrote:

> OK I have updated Android on my tablet so I am now testing on:
> 
> Phone: Samsung Galaxy SII (GT-I9100) with Android 4.1.2 (Jelly Bean)
> Tablet: Asus Transformer Prime (TF201) with Android 4.1.1 (Jelly Bean)
> 
> However, testing seems to show that Open networks are still not being
> removed. Here's an example of a test:
> 
> Created a Portable WiFi hotspot on my phone called "testing" (security set
> to "Open" and NOT "WPA PSK or WPA2 PSK")
> Ran Open WiFi Cleaner on my tablet just to make sure it is running and
> working ok (which it seems to be - both "Enabled" and "Notify on
> connect/disconnect" are checked)
> Connected to the "testing" hotspot from my tablet
> Connected back to my regular WiFi network on my tablet
> Result: The Open "testing" network is still listed and is not removed
> until I manually click to 'forget' it
> 
> Cheers,
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/duncanje/android-open-wifi-network-remover/issues/3#issuecomment-31586371
> .

## 

PGP public key -
http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xA3B79B579009DCA2

**Comment by BenKennish** [comment]
No notifications appeared for me.

It didn't work when my tablet was 4.0.3 (ICS) either.

Unfortunately, I cannot upgrade my phone or tablet to 4.2+ without using unofficial firmware which I'm reluctant to do.

Cheers,
Ben

**Comment by duncanje** [comment]
Ok, thanks. A couple more queries...
Did you install from the Play store?
Have you added any whitelist entries?
Have you tried clearing the app data for Open WiFi Cleaner?

I will try to sort a build that will output debug info at the weekend.

**Comment by duncanje** [comment]
Please find a debugging build [here](https://gist.github.com/duncanje/8378188/raw/58f2d70ce267065dd006068462151c58c8f88758/OpenWifiNetworkRemover.apk). It isn't signed with my Play store key so you will need to uninstall and then install the apk attached. This new apk is built off the 0.1.5.1-debug branch.

Please perform the connect/disconnect to an open access point as you have done previously. After this there should be an "Open Wifi Cleaner/debug" directory on your device's external storage. Please could you send the contents of this directory (the timestamped files contain some program flow and wifi scan details).

Thanks,
Duncan

**Comment by duncanje** [comment]
So, since I switched one of my devices to CyanogenMod I've noticed that my app has become very unreliable. I've made some changes which should benefit all devices.

0.1.5.2 is now rolling out in the Play store. This could well have fixed your issue so please test at your convenience.

Thanks,
Duncan

**Comment by BenKennish** [comment]
Hey Duncan,

Sorry I didn't get back to you.  Just thought I would report back that the bug now seems to be fixed in the current version of your app for both my phone and tablet.  :+1: 

There is a small problem with text though which I will report in a separate issue.
Cheers,
Ben

**Comment by duncanje** [comment]
Hi Ben,

Fab, thanks for letting me know! :)

Cheers,
Duncan
