### ISSUE TITLE
" will be forgotten"

### ISSUE THREAD

**Issue by BenKennish** [duncanje/android-open-wifi-network-remover#4]
When I connect to an Open WiFi with the app installed, the message " will be forgotten" is displayed in a message at the bottom of the display for a short period.

I assume that you are displaying the contents of a variable at the start (probably the SSID of the WiFi connection) but it seems that it is an empty string for me.

Tested on:
Phone: Samsung Galaxy SII (GT-I9100) with Android 4.1.2 (Jelly Bean)
Tablet: Asus Transformer Prime (TF201) with Android 4.1.1 (Jelly Bean)

Thanks for the great app.

PS: You might be interested to know that I have mentioned the app in a blog post I created recently : http://www.fubra.com/blog/2014/04/04/staying-safe-cyberspace/

**Comment by duncanje** [comment]
Thanks for letting me know. Strange that it's empty. You are correct, it should now display the SSID.

Please sign up to my test group: https://groups.google.com/forum/#!forum/dje-alpha-testers
Then join the Play Store test: https://play.google.com/apps/testing/com.dje.openwifinetworkremover

(It may take a couple of minutes before the 2nd link works)

You should then receive an update (to 0.1.6.2-dev-1) to the app through the Play Store.

Please could you let me know if that solves the problem? If it does, you can then leave the Play Store test group if you wish.

Thanks for mentioning the app in your blog post, it's nice to know it's useful for some! :)

**Comment by BenKennish** [comment]
It now says "Open network will be forgotten" on both the phone and tablet.  Is it supposed to say the SSID now?

**Comment by duncanje** [comment]
Sorry, I should have explained that better. There's not much I can do if the API returns an empty string when requesting the SSID, the documentation makes no mention of this ever happening.

So, in case of an empty string it will now fall back to saying Open network.

Thanks for testing.

**Comment by BenKennish** [comment]
No problem.  Thanks again for the app and for making it open source.  I keep meaning to brush up my Java and get involved in some Android app dev so maybe I'll take a look at some point soon :)

**Comment by duncanje** [comment]
No problem, fixes or enhancements are always welcome!
